name: CD

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project (set base for GitHub Pages)
        run: |
          export DEPLOY_TARGET=github
          npm run build

      - name: Copy Jest HTML report from main
        run: |
          git fetch origin main
          git checkout origin/main -- public/test/jest-report.html || echo "No test report found"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
