name: CI and CD

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    ci_cd:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 24
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Run Jest tests
              run: npm test

            - name: Copy Jest HTML report (if exists)
              run: |
                  mkdir -p dist/test
                  if [ -f jest-report.html ]; then
                    cp jest-report.html dist/test/
                  fi

            - name: Build project (set base for GitHub Pages)
              if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
              run: |
                  export DEPLOY_TARGET=github
                  npm run build

            - name: Deploy to GitHub Pages
              if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
