name: Fetch CNN Index
# 每天 UTC+8 上午8點，抓 cnn 指標儲存至 public/data/global.json

on:
    schedule:
        - cron: '0 8 * * *' # 每天 UTC+8 上午8點，台灣時間（UTC+8）要加上 8 小時 → 16:00（下午4點）。
    workflow_dispatch:

jobs:
    fetch-and-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install dependencies
              run: npm install
            - name: Fetch All Data
              run: node crawler/fetch-global-data.js
            - name: Commit & Push
              run: |
                  git config --global user.name 'github-actions'
                  git config --global user.email 'github-actions@github.com'
                  git add public/data/global.json
                  git commit -m 'Update all data'
                  git push

            # 因為 上面的 git push 不會觸發 CI/CD，所以這裡需要手動觸發
            - name: Build project (set base for GitHub Pages)
              run: |
                  export DEPLOY_TARGET=github
                  npm run build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
